name: axichat
description: "XMPP chat app."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.3.1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  drift: ^2.18.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  go_router: ^15.1.2
  hydrated_bloc: ^9.1.5
  json_annotation: ^4.9.0
  logging: ^1.2.0
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^12.0.0+1
  retry: ^3.1.2
  sqlcipher_flutter_libs: ^0.6.3
  moxxmpp:
    git:
      url: https://gitlab.com/axichat/moxxmpp.git
      path: packages/moxxmpp
  moxxmpp_socket_tcp:
    git:
      url: https://gitlab.com/axichat/moxxmpp.git
      path: packages/moxxmpp_socket_tcp
  crypto: ^3.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  freezed_annotation: ^2.4.1
  dash_chat_2: ^0.0.21
  hive_generator: ^2.0.1
  async: ^2.11.0
  mocktail: ^1.0.4
  shadcn_ui: ^0.27.0
  stream_transform: ^2.1.0
  emoji_picker_flutter: ^2.2.0
  animations: ^2.0.11
  libsignal_protocol_dart: ^0.7.1
  package_info_plus: ^8.3.0
  http: ^1.2.2
  xml: ^6.5.0
  hsluv: ^1.1.3
  flutter_foreground_task: ^9.1.0
  shorebird_code_push: ^2.0.3
  url_launcher: ^6.3.0
  flutter_local_notifications: ^19.1.0
  flutter_native_timezone:
    path: third_party/flutter_native_timezone
  timezone: ^0.10.0
  dnsolve: ^1.0.0
  app_settings: ^6.1.1
  intl: any
  chrono_dart: ^2.0.2

dependency_overrides:
  pinenacl: ^0.6.0
  intl: ^0.20.2
  moxxmpp:
    git:
      url: https://gitlab.com/axichat/moxxmpp.git
      path: packages/moxxmpp
      ref: f15a6a85227c408c330814652f209151ce16618d
  moxxmpp_socket_tcp:
    git:
      url: https://gitlab.com/axichat/moxxmpp.git
      path: packages/moxxmpp_socket_tcp
      ref: f15a6a85227c408c330814652f209151ce16618d

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  go_router_builder: ^2.7.0
  build_verify: ^3.1.0
  drift_dev: ^2.18.0
  lint: ^2.3.0
  freezed: ^2.5.2
  msix: ^3.16.8
  bloc_test: ^9.1.7
  change_app_package_name: ^1.5.0
  integration_test:
    sdk: flutter
  test: ^1.25.8



flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - shorebird.yaml
